### ISSUE TITLE
I don't get how this is different from sagas

### ISSUE THREAD

**Issue by jbrodriguez** [sskyy/redux-task#3]

**Comment by sskyy** [comment]
There are two major differences.

First, with saga you still need to dispatch different actions to track the pending/fulfilled/rejected state of an asynchronous task. redux-task track those state automatically for you.

Second, redux-saga listens from redux action while redux-task listens from custom event. So you know exactly an asynchronous task will be running when you emit a event, and state will change directly when you dispatch an action.

Check the docs. There are more differences.

**Comment by jbrodriguez** [comment]
Thanks @sskyy, I get it now
